repos:
    - repo: local
      hooks:
          - id: standard
            name: standard
            language: system
            types: ["ruby"]
            entry: bundle
            args: ["exec", "standardrb", "--fix"]
            pass_filenames: false
          - id: erb-format
            name: erb-format
            language: system
            types: ["erb"]
            entry: bundle
            args: ["exec", "erb-format", "--write", "--print-width", "120"]
          - id: prettier
            name: prettier
            language: system
            entry: npm
            args: ["exec", "prettier", "--", "--write", "--ignore-unknown"]
